name: publish-to-npm
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The updated registry version number.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          persist-credentials: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          scope: '@iorder-tech'

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
          git config user.name "${{ secrets.GIT_CONFIG_NAME }}"

      - name: Install Yarn
        run: npm install -g yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npm version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }} 📣"
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/iorder-tech/js-helper-kit.git
          git push

      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Create a new release on GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: 'Release notes for version ${{ github.event.inputs.version }}'
          draft: false
          prerelease: false
